# Generated by Django 5.0.4 on 2024-05-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
